{
 "title": "TOR Health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tor_relay_flag,instance)"
    }
   },
   {
    "name": "flag_type",
    "query": {
     "query": "label_values(tor_relay_flag,type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Circuits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tor_relay_circuits_total{instance=\"$instance\", state=\"opened\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opened Sokets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tor_relay_load_socket_total{instance=\"$instance\", state=\"opened\"}"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tor_relay_streams_total{instance=\"$instance\", type=\"BEGIN_DIR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flags",
   "type": "table",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "tor_relay_flag{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onion Skins last hour",
   "type": "bargauge",
   "description": "Onion Skins per second for last 1 hour",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(tor_relay_load_onionskins_total{instance=\"$instance\"}[1h])",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "Rate  Limit Reached",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tor_relay_load_global_rate_limit_reached_total{instance=\"$instance\"}",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": {
    "content": "![Tor Logo](https://www.torproject.org/static/images/tor-logo@2x.png)"
   }
  },
  {
   "title": "OOM per subsystem last hour",
   "type": "bargauge",
   "description": "OOM  per subsystem and TCP exaustion  in last 1 hour",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(tor_relay_load_oom_bytes_total{instance=\"$instance\"}[1h])",
     "legendFormat": "OOM in {{subsys}}"
    },
    {
     "expr": "rate(tor_relay_load_tcp_exhaustion_total{instance=\"$instance\"}[1h])",
     "legendFormat": "TCP Exaustion"
    }
   ]
  },
  {
   "title": "DNS Query times/second",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(tor_relay_exit_dns_query_total{instance=\"$instance\"}[1h])",
     "legendFormat": "Query  {{record}}"
    },
    {
     "expr": "sum by (record) (rate(tor_relay_exit_dns_error_total{instance=\"$instance\", reason!=\"success\"}[5m]))",
     "legendFormat": "Error {{record}}"
    }
   ]
  },
  {
   "title": "OR Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "tor_relay_connections{instance=\"$instance\", type=\"OR\"}",
     "legendFormat": "{{family}} {{direction}}"
    }
   ]
  },
  {
   "title": "Congestion Control",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "tor_relay_congestion_control{instance=\"$instance\"}",
     "legendFormat": "{{state}} {{action}}"
    }
   ]
  },
  {
   "title": "Onion Skins",
   "type": "timeseries",
   "description": "Onion Skins per second for last 1 hour",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(tor_relay_load_onionskins_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "DNS Stat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (reason) (rate(tor_relay_exit_dns_error_total{instance=\"$instance\", reason!=\"success\"}[5m]))",
     "legendFormat": "Failed - {{reason}}"
    },
    {
     "expr": "sum(rate(tor_relay_exit_dns_error_total{instance=\"$instance\", reason=\"success\"}[5m]))",
     "legendFormat": "successful"
    }
   ]
  },
  {
   "title": "OOM per subsystem and TCP exaustion ",
   "type": "timeseries",
   "description": "OOM per subsystem 5 min average",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(tor_relay_load_oom_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "OOM {{subsys}}"
    },
    {
     "expr": "rate(tor_relay_load_tcp_exhaustion_total{instance=\"$instance\"}[5m])",
     "legendFormat": "TCP exhaustion"
    }
   ]
  }
 ]
}